CREATE DATABASE LETSCAR;
GO
USE LETSCAR;
GO

CREATE TABLE CARRO (
    IDCARRO INTEGER PRIMARY KEY AUTOINCREMENT,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
    ANO INT NOT NULL,
    COR VARCHAR(30) NOT NULL,
    PRECO DECIMAL (10,1) NOT NULL,
    ADICIONAIS VARCHAR(100) NOT NULL,
);

CREATE TABLE CLIENTE (
    IDCLIENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE BIGINT NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    IDFAVORITO INT NOT NULL,
    IDCARRO INT NOT NULL,
    
    CONSTRAINT FK_CARRODOCLIENTE
    FOREIGN KEY(IDCARRO)
    REFERENCES CARRO(IDCARRO),

    CONSTRAINT FK_FAVORITODOCLIENTE
    FOREIGN KEY(IDFAVORITO)
    REFERENCES FAVORITO(IDFAVORITO),
    
);

CREATE TABLE FORMAPAGAMENTO(
    IDFORMAPAGAMENTO INTEGER PRIMARY KEY AUTOINCREMENT,
    BOLETO BIT(1) NOT NULL,
    PIX BIT(1) NOT NULL,
    DINHEIRO BIT(1) NOT NULL,
    CARTAO BIT(1) NOT NULL,
    IDCARRO INT NOT NULL,

    CONSTRAINT FK_FORMAPAGAMENTOEMCARRO 
    FOREIGN KEY(IDCARRO)
    REFERENCES CARRO(IDCARRO),
);


CREATE TABLE ADICIONAIS(
    IDADICIONAIS INTEGER PRIMARY KEY AUTOINCREMENT,
    AR BIT(1) NOT NULL,
    VIDRO BIT(1) NOT NULL,
    TRAVA BIT(1) NOT NULL,
    IDCARRO INT NOT NULL

    CONSTRAINT FK_ADICIONAISNOCARRO 
    FOREIGN KEY(IDCARRO)
    REFERENCES CARRO(IDCARRO)
);


CREATE TABLE FORMULARIOCONTATO(
    IDFORMULARIOCONTATO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMECOMPLETO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    TELEFONE BIGINT NOT NULL,
    DESCRICAOMENSAGEM VARCHAR(256) NOT NULL,
    MODELO VARCHAR(50) NOT NULL
    IDCARRO INT NOT NULL,
    
    CONSTRAINT FK_CARROCOMCONTATO 
    FOREIGN KEY(IDCARRO)
    REFERENCES CARRO(IDCARRO)
);


CREATE TABLE FAVORITO(
    IDFAVORITO INTEGER PRIMARY KEY AUTOINCREMENT
    IDCLIENTE INT NOT NULL,
    IDCARRO INT NOT NULL,

    CONSTRAINT FK_CLIENTEFAVORITOU 
    FOREIGN KEY(IDCLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)

    CONSTRAINT FK_CARROFAVORITADO 
    FOREIGN KEY(IDCARRO)
    REFERENCES CARRO(IDCARRO)
);