--CARRO
-- INSERÇÃO
GO
CREATE PROCEDURE INSERCAOCARRO
@MARCA VARCHAR(50),
@MODELO VARCHAR(50),
@ANO INT,
@COR VARCHAR(30),
@PRECO DECIMAL(10,1),
@ADICIONAIS VARCHAR(100)
AS
BEGIN
    INSERT INTO CARRO(MARCA, MODELO, ANO, COR, PRECO, ADICIONAIS)
    VALUES(@MARCA, @MODELO, @ANO, @COR, @PRECO, @ADICIONAIS);
END
GO

--EXCLUSÃO
GO
CREATE PROCEDURE EXCLUSAOCARRO
@IDCARRO INT
AS
BEGIN
    DELETE FROM CARRO WHERE IDCARRO = @IDCARRO;
END
GO


--EDICAO
GO
CREATE PROCEDURE EDITARCARRO
@IDCARRO INT,
@MARCA VARCHAR(50),
@MODELO VARCHAR(50),
@ANO INT,
@COR VARCHAR(30),
@PRECO DECIMAL(10,1),
@ADICIONAIS VARCHAR(100)
AS
BEGIN
    UPDATE CARRO
    SET
        MARCA = @MARCA,
        MODELO = @MODELO,
        ANO = @ANO,
        COR = @COR,
        PRECO = @PRECO,
        ADICIONAIS = @ADICIONAIS
    WHERE
        IDCARRO = @IDCARRO
END
GO

--SELECT CARRO QUE PERTENÇA A UM CLIENTE 
GO
CREATE PROCEDURE SELECTCLIENTETEMCARRO
AS
BEGIN
    SELECT CARRO.MARCA, CARRO.MODELO, CLIENTE.NOME AS 'CLIENTE'
    FROM CARRO
    INNER JOIN CLIENTE ON CARRO.IDCARRO = CLIENTE.IDCLIENTE
END
GO

--SELECT CLIENTE QUE TENHA FAVORITO
GO
CREATE PROCEDURE SELECTCLIENTETEMCARRO
AS
BEGIN
    SELECT CLIENTE.NOME AS 'CLIENTES QUE FAVORITARAM'
    FROM FAVORITO
    INNER JOIN CLIENTE ON FAVORITO.IDFAVORITO = CLIENTE.IDCLIENTE
END
GO

