--FORMA DE PAGAMENTO

-- INSERÇÃO
GO
CREATE PROCEDURE INSERCAOFORMAPAGAMENTO
@BOLETO BIT(1),
@PIX BIT(1),
@DINHEIRO BIT(1),
@CARTAO BIT(1)
AS
BEGIN
    INSERT INTO FORMAPAGAMENTO(BOLETO, PIX, DINHEIRO, CARTAO)
    VALUES(@BOLETO, @PIX, @DINHEIRO, @CARTAO);
END
GO

--EXCLUSÃO
GO
CREATE PROCEDURE EXCLUSAOFORMAPAGAMENTO
@IDFORMAPAGAMENTO INT
AS
BEGIN
    DELETE FROM FORMAPAGAMENTO WHERE IDFORMAPAGAMENTO = @IDFORMAPAGAMENTO;
END
GO


--EDICAO
GO
CREATE PROCEDURE EDITARFORMAPAGAMENTO
@IDFORMAPAGAMENTO INT
@BOLETO BIT(1),
@PIX BIT(1),
@DINHEIRO BIT(1),
@CARTAO BIT(1)
AS
BEGIN
    UPDATE FORMAPAGAMENTO
    SET
        BOLETO = @BOLETO,
        PIX = @PIX,
        DINHEIRO = @DINHEIRO,
        CARTAO = @CARTAO
    WHERE
        IDFORMAPAGAMENTO = @IDFORMAPAGAMENTO
END
GO

--SELECT FORMAPAGAMENTO DO CARRO
GO
CREATE PROCEDURE SELECTFORMAPAGAMENTOCARRO
AS
BEGIN
    SELECT FORMAPAGAMENTO.BOLETO, FORMAPAGAMENTO.CARTAO, FORMAPAGAMENTO.DINHEIRO, FORMAPAGAMENTO.PIX, CARRO.MARCA, CARRO.MODELO
    FROM FORMAPAGAMENTO 
    INNER JOIN CARRO ON FORMAPAGAMENTO.IDFORMAPAGAMENTO = CARRO.IDCARRO;
END
GO
