--FORMULÁRIO DE CONTATO

-- INSERÇÃO
GO
CREATE PROCEDURE INSERCAOFORMULARIOCONTATO
@NOMECOMPLETO VARCHAR(100),
@EMAIL VARCHAR(256),
@TELEFONE BIGINT,
@DESCRICAOMENSAGEM VARCHAR(256),
@MODELO VARCHAR(50)
AS
BEGIN
    INSERT INTO FORMULARIOCONTATO(NOMECOMPLETO, EMAIL, TELEFONE, DESCRICAOMENSAGEM, MODELO)
    VALUES(@NOMECOMPLETO, @EMAIL, @TELEFONE, @DESCRICAOMENSAGEM, @MODELO);
END
GO

--EXCLUSÃO
GO
CREATE PROCEDURE EXCLUSAOFORMULARIOCONTATO
@IDFORMULARIOCONTATO INT
AS
BEGIN
    DELETE FROM FORMULARIOCONTATO WHERE IDFORMULARIOCONTATO = @FORMULARIOCONTATO;
END
GO


--EDICAO
GO
CREATE PROCEDURE EDITARFORMULARIOCONTATO
@IDFORMULARIOCONTATO INT
@NOMECOMPLETO VARCHAR(100),
@EMAIL VARCHAR(256),
@TELEFONE BIGINT,
@DESCRICAOMENSAGEM VARCHAR(256),
@MODELO VARCHAR(50)
AS
BEGIN
    UPDATE FORMULARIOCONTATO
    SET
        IDFORMULARIOCONTATO = @IDFORMULARIOCONTATO,
        NOMECOMPLETO = @NOMECOMPLETO,
        EMAIL = @EMAIL,
        TELEFONE = @TELEFONE,
        DESCRICAOMENSAGEM = @DESCRICAOMENSAGEM,
        MODELO = @MODELO
    WHERE
        IDFORMULARIOCONTATO = @IDFORMULARIOCONTATO
END
GO

--SELECT FORMULARIOCONTATO DO CARRO
GO
CREATE PROCEDURE SELECTFORMULARIOCONTATOCARRO
AS
BEGIN
    SELECT FORMULARIOCONTATO.DESCRICAOMENSAGEM, CARRO.MODELO AS 'MODELO DO CARRO'
    FROM FORMULARIOCONTATO 
    INNER JOIN CARRO ON FORMULARIOCONTATO.IDFORMULARIOCONTATO = CARRO.IDCARRO;
END
GO


