--ADICIONAIS

-- INSERÇÃO
GO
CREATE PROCEDURE INSERCAO_ADICIONAIS
@AR BIT(1),
@VIDRO BIT(1),
@TRAVA BIT(1)
AS
BEGIN
    INSERT INTO ADICIONAIS(AR, VIDRO, TRAVA)
    VALUES(@AR, @VIDRO, @TRAVA);
END
GO

--EXCLUSÃO
GO
CREATE PROCEDURE EXCLUSAO_ADICIONAIS
@IDADICIONAIS INT
AS
BEGIN
    DELETE FROM ADICIONAIS  WHERE IDADICIONAIS  = @IDADICIONAIS ;
END
GO


--EDICAO
GO
CREATE PROCEDURE EDITARFORMULARIOCONTATO
@IDADICIONAIS INT
@AR BIT(1),
@VIDRO BIT(1),
@TRAVA BIT(1)
AS
BEGIN
    UPDATE ADICIONAIS
    SET
        @IDADICIONAIS = IDADICIONAIS,
        @AR = AR,
        @VIDRO = VIDRO,
        @TRAVA = TRAVA
    WHERE
        IDADICIONAIS = @IDADICIONAIS
END
GO

--SELECT ADICIONAIS DO CARRO
GO
CREATE PROCEDURE SELECT_ADICIONAIS_CARRO
AS
BEGIN
    SELECT ADICIONAIS.AR, ADICIONAIS.TRAVA, ADICIONAIS.VIDRO, CARRO.MODELO AS 'MODELO DO CARRO'
    FROM ADICIONAIS 
    INNER JOIN CARRO ON ADICIONAIS.IDADICIONAIS = CARRO.IDCARRO;
END
GO




