--FAVORITO

-- INSERÇÃO
GO
CREATE PROCEDURE INSERCAO_FAVORITO
@IDCLIENTE INT,
@IDCARRO INT,
AS
BEGIN
    INSERT INTO FAVORITOS(IDCLIENTE, IDCARRO)
    VALUES(@IDCLIENTE, @IDCARRO);
END
GO

--EXCLUSÃO
GO
CREATE PROCEDURE EXCLUSAO_FAVORITO
@IDFAVORITO INT
AS
BEGIN
    DELETE FROM FAVORITO  WHERE IDFAVORITO  = @IDFAVORITO;
END
GO


--EDICAO
GO
CREATE PROCEDURE EDITAR_FAVORITO
@IDFAVORITO INT,
@IDCARRO INT
AS
BEGIN
    UPDATE FAVORITO
    SET
        @IDCARRO = IDCARRO
    WHERE
        IDFAVORITO = @IDFAVORITO
END
GO

--SELECT FAVORITOS DO CARRO
GO
CREATE PROCEDURE SELECT_FAVORITOS_CARRO
AS
BEGIN
    SELECT FAVORITO.IDFAVORITO, FAVORITO.IDCARRO, FAVORITO.IDCLIENTE, CARRO.MODELO AS 'MODELO DO CARRO'
    FROM FAVORITO 
    INNER JOIN CARRO ON FAVORITO.IDFAVORITO = CARRO.IDCARRO;
END
GO

--SELECT TODOS OS FAVORITOS DOS CLIENTES
GO
CREATE PROCEDURE SELECT_FAVORITOS_CLIENTE
AS
BEGIN
    SELECT *
    FROM FAVORITO 
    INNER JOIN CLIENTE ON FAVORITO.IDFAVORITO = CLIENTE.IDCLIENTE;
END
GO




